[workspace]
resolver = "2"
members = [
    "crates/khora-syntax",
    "crates/khora-hir",
    "crates/khora-types",
    "crates/khora-perceus",
    "crates/khora-codegen-llvm",
    "crates/khora-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
license = "MIT OR Apache-2.0"
repository = "https://github.com/khora-lang/khora"

[workspace.dependencies]
khora-syntax = { path = "crates/khora-syntax" }
khora-hir = { path = "crates/khora-hir" }
khora-types = { path = "crates/khora-types" }
khora-perceus = { path = "crates/khora-perceus" }
khora-codegen-llvm = { path = "crates/khora-codegen-llvm" }

logos = "0.15"
rowan = "0.17"
text-size = "1.1"
rustc-hash = "2"
smol_str = "0.3"
anyhow = "1"
clap = { version = "4", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
