[workspace]
resolver = "2"
members = [
    "crates/khora-syntax",
    "crates/khora-db",
    "crates/khora-fmt",
    "crates/khora-diagnostics",
    "crates/khora-hir",
    "crates/khora-types",
    "crates/khora-perceus",
    "crates/khora-rt",
    "crates/khora-codegen-llvm",
    "crates/khora-manifest",
    "crates/khora-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
license = "MIT OR Apache-2.0"
repository = "https://github.com/khora-lang/khora"

[workspace.dependencies]
khora-syntax = { path = "crates/khora-syntax" }
khora-db = { path = "crates/khora-db" }
khora-fmt = { path = "crates/khora-fmt" }
khora-diagnostics = { path = "crates/khora-diagnostics" }
khora-hir = { path = "crates/khora-hir" }
khora-types = { path = "crates/khora-types" }
khora-perceus = { path = "crates/khora-perceus" }
khora-rt = { path = "crates/khora-rt" }
khora-codegen-llvm = { path = "crates/khora-codegen-llvm" }
khora-manifest = { path = "crates/khora-manifest" }

salsa = "0.28"
logos = "0.15"
rowan = "0.17"
text-size = "1.1"
rustc-hash = "2"
smol_str = "0.3"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
