//! A [`Module`] as a documentation page.
//!
//! Starlight markdown, because that is what `website/` builds. The only
//! Starlight-specific part is the frontmatter; everything below it is ordinary
//! CommonMark and would render anywhere.
//!
//! **The output is a pure function of the input.** No timestamp, no compiler
//! version, no path from the machine that ran it -- so regenerating after a
//! change produces a diff that is exactly the change, and regenerating after no
//! change produces no diff at all. A generated file that always differs from
//! itself is a generated file nobody can review.

use crate::links::{Slugger, Targets, resolved};
use crate::{Item, Kind, Module, SECTIONS, base_name};

/// One module's page.
///
/// **Written twice.** A doc comment can name another item on the page, and the
/// anchor it has to link to is not known until the page has been laid out --
/// the first `List::map` on `std::core` is `#map`, the second is `#map-1`, and
/// which is which is decided by heading order. So the first pass lays the page
/// out and is thrown away for everything but the anchors it found, and the
/// second writes it with the references pointing at them.
///
/// The two passes agree about where every heading lands because an anchor is
/// taken from a heading's *rendered* text, and resolving a reference does not
/// change that: a bracketed `Raw`, a bare `Raw` and a linked `Raw` all render
/// as `Raw`.
pub fn markdown(module: &Module) -> String {
    let (_, targets) = page(module, &Targets::default());
    page(module, &targets).0
}

/// The page, and every anchor a reference could name on it.
fn page(module: &Module, targets: &Targets) -> (String, Targets) {
    let title = module.path.clone().unwrap_or_else(|| "(no module)".to_string());
    let mut page = Page {
        out: String::new(),
        slugger: Slugger::default(),
        found: Targets::default(),
        targets,
    };

    page.out.push_str("---\n");
    page.out.push_str(&format!("title: {title}\n"));
    if let Some(summary) = summary(&module.doc) {
        page.out.push_str(&format!("description: {}\n", quoted(&summary)));
    }
    page.out.push_str("---\n\n");

    // **An HTML comment and not `{/* */}`.** These are `.md` files, and the
    // JSX form is MDX syntax that plain markdown renders as literal text --
    // so the note meant for whoever opens the file would have appeared at the
    // top of the page instead. Said once, at the top, either way.
    page.out.push_str(&format!(
        "<!-- Generated by `khora doc` from the `///` and `//!` comments in \
         `{title}`. Edits here are overwritten; change the source. -->\n\n"
    ));

    // Shifted by one: the page title is the `h1`, so a `#` written in the
    // module's own text is a sibling of `## Types` and not its parent.
    page.prose(&module.doc, 1, None);

    if module.items.is_empty() {
        page.out.push_str("This module exports nothing.\n");
        return page.finish();
    }

    for kind in SECTIONS {
        let group: Vec<&Item> = module.items.iter().filter(|i| i.kind == *kind).collect();
        if group.is_empty() {
            continue;
        }
        page.heading(2, kind.heading());
        for item in group {
            page.entry(item, 3);
        }
    }
    page.finish()
}

/// The page as it is being written, and what a later reference will need.
struct Page<'a> {
    out: String,
    slugger: Slugger,
    found: Targets,
    targets: &'a Targets,
}

impl Page<'_> {
    fn finish(self) -> (String, Targets) {
        (self.out, self.found)
    }

    /// One heading, and the anchor it takes.
    ///
    /// Everything that emits a heading goes through here, the section headings
    /// included: an anchor depends on how many headings with the same text
    /// came before it, so one that skipped the count would move every anchor
    /// under it.
    fn heading(&mut self, depth: usize, text: &str) -> String {
        let line = format!("{} {}", "#".repeat(depth.min(6)), text);
        let anchor = self.slugger.slug(&line);
        self.out.push_str(&line);
        self.out.push_str("\n\n");
        anchor
    }

    /// A block of doc text, shifted below the heading it sits under and with
    /// its references resolved.
    fn prose(&mut self, doc: &[String], depth: usize, scope: Option<&str>) {
        if doc.is_empty() {
            return;
        }
        let text = resolved(&shifted(doc, depth), self.targets, scope);
        // A heading an author wrote is a heading on the built page, and takes
        // its anchor from the same counter as the generated ones.
        let mut fenced = false;
        for line in text.split('\n') {
            if line.trim_start().starts_with("```") {
                fenced = !fenced;
            } else if !fenced && line.starts_with('#') {
                self.slugger.slug(line);
            }
        }
        self.out.push_str(&text);
        self.out.push_str("\n\n");
    }

    fn signature(&mut self, item: &Item) {
        if item.signature.is_empty() {
            return;
        }
        self.out.push_str("```khora\n");
        self.out.push_str(&item.signature);
        self.out.push_str("\n```\n\n");
    }

    /// One item, with its members under it.
    fn entry(&mut self, item: &Item, depth: usize) {
        let anchor = self.heading(depth, &item.name);
        // `impl Array<A>` is headed `Array<A>` and is referred to as `Array`.
        // A trait impl is headed `Show for Int`, whose first word is the
        // trait's -- claiming it would send a reference to `Show` to one
        // arbitrary implementation rather than to the trait, so it claims no
        // name at all and the trait's own heading keeps it.
        let scope = (item.kind != Kind::TraitImpl).then(|| base_name(&item.name).to_string());
        if let Some(scope) = &scope {
            self.found.record(scope.clone(), &anchor);
        }
        self.signature(item);
        self.prose(&item.doc, depth, scope.as_deref());

        // **A field or a case with nothing said about it is not repeated.** It
        // is already in the signature block directly above -- a `## Fields`
        // section that restates `units: Int` under its own heading is three
        // lines that add nothing, and it buries the ones that do have
        // something to say.
        let worth_saying = |m: &&Item| match m.kind {
            Kind::Field | Kind::Variant => !m.doc.is_empty(),
            // **An operation is listed whether or not it is documented.** A
            // record field with nothing to say is noise beside a signature
            // that already shows it; an effect's operation is the thing a
            // caller writes, and a list missing half of them is worse than one
            // with a bare entry.
            _ => true,
        };

        // **A case with nothing said about it still has somewhere to send a
        // reference.** It gets no heading of its own, by the rule above, but
        // it is right there in the declaration block under this item's
        // heading -- so a reference to `Raw::Absent` goes to `Raw` rather than
        // losing its brackets over a case the page does show.
        if let Some(scope) = &scope {
            for member in item.members.iter().filter(|m| !worth_saying(m)) {
                self.found.record_weak(format!("{scope}::{}", member.name), &anchor);
            }
        }

        let kinds: Vec<Kind> =
            [Kind::Variant, Kind::Field, Kind::Operation, Kind::AssocType, Kind::Function]
                .into_iter()
                .filter(|k| item.members.iter().filter(worth_saying).any(|m| m.kind == *k))
                .collect();

        for kind in &kinds {
            let group: Vec<&Item> =
                item.members.iter().filter(worth_saying).filter(|m| m.kind == *kind).collect();
            // The group heading earns its place only when there is more than
            // one kind of member to separate. `impl Decimal` has methods and
            // nothing else, and a `Functions` heading between the type and its
            // methods is a level of nesting that says nothing and pushes every
            // method past the depth a sidebar will show.
            let inner = if kinds.len() > 1 {
                self.heading(depth + 1, kind.heading());
                depth + 2
            } else {
                depth + 1
            };
            for member in group {
                self.member(member, inner, scope.as_deref());
            }
        }
    }

    fn member(&mut self, item: &Item, depth: usize, scope: Option<&str>) {
        let anchor = self.heading(depth, &item.name);
        if let Some(scope) = scope {
            self.found.record(format!("{scope}::{}", item.name), &anchor);
        }
        self.signature(item);
        self.prose(&item.doc, depth, scope);
    }
}

/// Doc text with its own headings pushed below the heading it sits under.
///
/// A `# What a Decimal is` written in a doc comment is a heading *within that
/// item*, and emitting it as written would put it above the module's own `##`
/// sections and scatter the page's table of contents. Shifting keeps the
/// nesting the author meant.
///
/// A fenced block is copied through untouched, because a `#` in one is a
/// comment or a shell prompt and not a heading.
fn shifted(lines: &[String], depth: usize) -> String {
    let mut out: Vec<String> = Vec::with_capacity(lines.len());
    let mut fenced = false;
    for line in lines {
        if line.trim_start().starts_with("```") {
            fenced = !fenced;
            out.push(line.clone());
            continue;
        }
        if !fenced && line.starts_with('#') {
            let hashes = line.chars().take_while(|c| *c == '#').count();
            let rest = &line[hashes..];
            out.push(format!("{}{}", "#".repeat((hashes + depth).min(6)), rest));
            continue;
        }
        out.push(line.clone());
    }
    out.join("\n")
}

/// The first sentence of the doc, for the frontmatter description.
///
/// Starlight puts it in the page's `<meta>` and in search results, where a
/// paragraph is worse than nothing. Headings and fenced blocks are skipped: a
/// module whose text opens with `# Overview` should be described by what
/// follows it.
///
/// **The paragraph is rejoined before the sentence is cut out of it.** A doc
/// comment is wrapped to fit a source file, so the first *line* ends wherever
/// eighty columns fell -- taking that as the description produced
/// "Exact decimal arithmetic, for the numbers that are counted rather than",
/// which is worse than no description because it looks deliberate.
fn summary(doc: &[String]) -> Option<String> {
    let mut paragraph = String::new();
    let mut fenced = false;
    for line in doc {
        if line.trim_start().starts_with("```") {
            fenced = !fenced;
            continue;
        }
        if fenced || line.starts_with('#') {
            continue;
        }
        if line.trim().is_empty() {
            if paragraph.is_empty() {
                continue;
            }
            break;
        }
        if !paragraph.is_empty() {
            paragraph.push(' ');
        }
        paragraph.push_str(line.trim());
    }
    if paragraph.is_empty() {
        return None;
    }
    let sentence = match paragraph.find(". ") {
        Some(at) => &paragraph[..at],
        None => paragraph.trim_end_matches('.'),
    };
    Some(plain(sentence.trim_end_matches('.')))
}

/// Markdown emphasis and code markers removed, for somewhere they do not render.
///
/// One pass over both characters rather than a pass for `**` and another for
/// `*`: the second subsumes the first, so the pair was doing nothing.
fn plain(text: &str) -> String {
    text.replace(['`', '*'], "")
}

/// A YAML scalar that will survive whatever is in it.
///
/// Always quoted and always escaped, rather than quoting only when it looks
/// necessary: the cases that need it are a colon and a leading `` ` ``, both of
/// which appear constantly in this project's prose, and a rule with exceptions
/// is a rule that gets one wrong.
fn quoted(text: &str) -> String {
    format!("\"{}\"", text.replace('\\', "\\\\").replace('"', "\\\""))
}
