//! A [`Module`] as a documentation page.
//!
//! Starlight markdown, because that is what `website/` builds. The only
//! Starlight-specific part is the frontmatter; everything below it is ordinary
//! CommonMark and would render anywhere.
//!
//! **The output is a pure function of the input.** No timestamp, no compiler
//! version, no path from the machine that ran it -- so regenerating after a
//! change produces a diff that is exactly the change, and regenerating after no
//! change produces no diff at all. A generated file that always differs from
//! itself is a generated file nobody can review.

use crate::{Item, Kind, Module, SECTIONS};

/// One module's page.
pub fn markdown(module: &Module) -> String {
    let title = module.path.clone().unwrap_or_else(|| "(no module)".to_string());
    let mut out = String::new();

    out.push_str("---\n");
    out.push_str(&format!("title: {title}\n"));
    if let Some(summary) = summary(&module.doc) {
        out.push_str(&format!("description: {}\n", quoted(&summary)));
    }
    out.push_str("---\n\n");

    // **An HTML comment and not `{/* */}`.** These are `.md` files, and the
    // JSX form is MDX syntax that plain markdown renders as literal text --
    // so the note meant for whoever opens the file would have appeared at the
    // top of the page instead. Said once, at the top, either way.
    out.push_str(&format!(
        "<!-- Generated by `khora doc` from the `///` and `//!` comments in \
         `{title}`. Edits here are overwritten; change the source. -->\n\n"
    ));

    if !module.doc.is_empty() {
        // Shifted by one: the page title is the `h1`, so a `#` written in the
        // module's own text is a sibling of `## Types` and not its parent.
        out.push_str(&shifted(&module.doc, 1));
        out.push_str("\n\n");
    }

    if module.items.is_empty() {
        out.push_str("This module exports nothing.\n");
        return out;
    }

    for kind in SECTIONS {
        let group: Vec<&Item> = module.items.iter().filter(|i| i.kind == *kind).collect();
        if group.is_empty() {
            continue;
        }
        out.push_str(&format!("## {}\n\n", kind.heading()));
        for item in group {
            entry(&mut out, item, 3);
        }
    }
    out
}

/// One item, with its members under it.
fn entry(out: &mut String, item: &Item, depth: usize) {
    out.push_str(&format!("{} {}\n\n", "#".repeat(depth), item.name));
    if !item.signature.is_empty() {
        out.push_str("```khora\n");
        out.push_str(&item.signature);
        out.push_str("\n```\n\n");
    }
    if !item.doc.is_empty() {
        out.push_str(&shifted(&item.doc, depth));
        out.push_str("\n\n");
    }

    // **A field or a case with nothing said about it is not repeated.** It is
    // already in the signature block directly above -- a `## Fields` section
    // that restates `units: Int` under its own heading is three lines that add
    // nothing, and it buries the ones that do have something to say.
    let worth_saying = |m: &&Item| match m.kind {
        Kind::Field | Kind::Variant => !m.doc.is_empty(),
        _ => true,
    };

    let kinds: Vec<Kind> = [Kind::Variant, Kind::Field, Kind::AssocType, Kind::Function]
        .into_iter()
        .filter(|k| item.members.iter().filter(worth_saying).any(|m| m.kind == *k))
        .collect();

    for kind in &kinds {
        let group: Vec<&Item> =
            item.members.iter().filter(worth_saying).filter(|m| m.kind == *kind).collect();
        // The group heading earns its place only when there is more than one
        // kind of member to separate. `impl Decimal` has methods and nothing
        // else, and a `Functions` heading between the type and its methods is
        // a level of nesting that says nothing and pushes every method past
        // the depth a sidebar will show.
        let inner = if kinds.len() > 1 {
            out.push_str(&format!("{} {}\n\n", "#".repeat(depth + 1), kind.heading()));
            depth + 2
        } else {
            depth + 1
        };
        for member in group {
            member_entry(out, member, inner);
        }
    }
}

fn member_entry(out: &mut String, item: &Item, depth: usize) {
    out.push_str(&format!("{} {}\n\n", "#".repeat(depth.min(6)), item.name));
    if !item.signature.is_empty() {
        out.push_str("```khora\n");
        out.push_str(&item.signature);
        out.push_str("\n```\n\n");
    }
    if !item.doc.is_empty() {
        out.push_str(&shifted(&item.doc, depth));
        out.push_str("\n\n");
    }
}

/// Doc text with its own headings pushed below the heading it sits under.
///
/// A `# What a Decimal is` written in a doc comment is a heading *within that
/// item*, and emitting it as written would put it above the module's own `##`
/// sections and scatter the page's table of contents. Shifting keeps the
/// nesting the author meant.
///
/// A fenced block is copied through untouched, because a `#` in one is a
/// comment or a shell prompt and not a heading.
fn shifted(lines: &[String], depth: usize) -> String {
    let mut out: Vec<String> = Vec::with_capacity(lines.len());
    let mut fenced = false;
    for line in lines {
        if line.trim_start().starts_with("```") {
            fenced = !fenced;
            out.push(line.clone());
            continue;
        }
        if !fenced && line.starts_with('#') {
            let hashes = line.chars().take_while(|c| *c == '#').count();
            let rest = &line[hashes..];
            out.push(format!("{}{}", "#".repeat((hashes + depth).min(6)), rest));
            continue;
        }
        out.push(line.clone());
    }
    out.join("\n")
}

/// The first sentence of the doc, for the frontmatter description.
///
/// Starlight puts it in the page's `<meta>` and in search results, where a
/// paragraph is worse than nothing. Headings and fenced blocks are skipped: a
/// module whose text opens with `# Overview` should be described by what
/// follows it.
///
/// **The paragraph is rejoined before the sentence is cut out of it.** A doc
/// comment is wrapped to fit a source file, so the first *line* ends wherever
/// eighty columns fell -- taking that as the description produced
/// "Exact decimal arithmetic, for the numbers that are counted rather than",
/// which is worse than no description because it looks deliberate.
fn summary(doc: &[String]) -> Option<String> {
    let mut paragraph = String::new();
    let mut fenced = false;
    for line in doc {
        if line.trim_start().starts_with("```") {
            fenced = !fenced;
            continue;
        }
        if fenced || line.starts_with('#') {
            continue;
        }
        if line.trim().is_empty() {
            if paragraph.is_empty() {
                continue;
            }
            break;
        }
        if !paragraph.is_empty() {
            paragraph.push(' ');
        }
        paragraph.push_str(line.trim());
    }
    if paragraph.is_empty() {
        return None;
    }
    let sentence = match paragraph.find(". ") {
        Some(at) => &paragraph[..at],
        None => paragraph.trim_end_matches('.'),
    };
    Some(plain(sentence.trim_end_matches('.')))
}

/// Markdown emphasis and code markers removed, for somewhere they do not render.
///
/// One pass over both characters rather than a pass for `**` and another for
/// `*`: the second subsumes the first, so the pair was doing nothing.
fn plain(text: &str) -> String {
    text.replace(['`', '*'], "")
}

/// A YAML scalar that will survive whatever is in it.
///
/// Always quoted and always escaped, rather than quoting only when it looks
/// necessary: the cases that need it are a colon and a leading `` ` ``, both of
/// which appear constantly in this project's prose, and a rule with exceptions
/// is a rule that gets one wrong.
fn quoted(text: &str) -> String {
    format!("\"{}\"", text.replace('\\', "\\\\").replace('"', "\\\""))
}
