[package]
name = "khora-types"
description = "Hindley-Milner inference with scoped row polymorphism and const generics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
khora-hir.workspace = true
text-size.workspace = true
salsa.workspace = true
khora-syntax.workspace = true
khora-db.workspace = true
rustc-hash.workspace = true
