//! The C header a library publishes.
//!
//! Generated from the same signatures the checker validated, rather than
//! written by hand. A header that can drift from its source is a header that
//! will, and the failure is silent in the worst way: the caller compiles
//! against a prototype the library does not have, and the mismatch is a
//! calling-convention bug rather than a link error.
//!
//! Only the types `docs/design/ffi.md` §1 allows appear here, because the
//! checker refused everything else at the declaration — see
//! `khora-types/src/exports.rs`. So there is no case in this file for "a type
//! that cannot cross": by the time a signature reaches it, one cannot exist.

use std::fmt::Write as _;

use khora_types::{Signature, Type};

/// Renders a header declaring `exports`, in the order given.
///
/// `guard` is the include guard's stem — the library's name.
pub(crate) fn render(guard: &str, exports: &[(String, Signature)]) -> String {
    let macro_name = format!("KHORA_{}_H", shout(guard));
    let mut out = String::new();

    let _ = writeln!(out, "/* Generated by khora. Do not edit: rebuild instead. */");
    let _ = writeln!(out, "#ifndef {macro_name}");
    let _ = writeln!(out, "#define {macro_name}");
    out.push('\n');
    // `stdint.h` for the fixed widths, `stdbool.h` because `Bool` is `_Bool`
    // and C code is entitled to spell it `bool`.
    let _ = writeln!(out, "#include <stdbool.h>");
    let _ = writeln!(out, "#include <stdint.h>");
    out.push('\n');
    let _ = writeln!(out, "#ifdef __cplusplus");
    let _ = writeln!(out, "extern \"C\" {{");
    let _ = writeln!(out, "#endif");
    out.push('\n');

    // **The control surface, before the exports.** A host that wants to survive
    // a trap should not have to hand-write `extern` declarations for functions
    // the library already publishes — that is how a prototype drifts from the
    // symbol it names, which is the whole reason this file is generated.
    // `docs/design/c-export.md` §8.
    let _ = writeln!(out, "/* Trap containment. Off by default: without the call below a trap");
    let _ = writeln!(out, "   ends the process, which is what a program wants and a library");
    let _ = writeln!(out, "   does not. See docs/design/traps.md. */");
    let _ = writeln!(out, "void khora_set_trap_policy(int contain);");
    let _ = writeln!(out, "int khora_trapped(void);");
    let _ = writeln!(out, "void khora_clear_trap(void);");
    out.push('\n');
    let _ = writeln!(out, "/* Diagnostic, not a contract: docs/design/compatibility.md says");
    let _ = writeln!(out, "   allocation behaviour is not part of the language's promise. Here");
    let _ = writeln!(out, "   because a host just told a trap was contained is entitled to");
    let _ = writeln!(out, "   check that the memory came back. */");
    let _ = writeln!(out, "long long khora_live_count(void);");
    let _ = writeln!(out, "long long khora_alloc_count(void);");
    out.push('\n');

    for (name, signature) in exports {
        let params = if signature.params.is_empty() {
            // **`void`, not `()`.** An empty parameter list in C is a function
            // that takes *unspecified* arguments, which silences every check a
            // caller would otherwise get.
            "void".to_string()
        } else {
            signature
                .params
                .iter()
                .enumerate()
                .map(|(i, ty)| format!("{} a{i}", c_type(ty)))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(out, "{} {name}({params});", c_type(&signature.ret));
    }

    out.push('\n');
    let _ = writeln!(out, "#ifdef __cplusplus");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "#endif");
    out.push('\n');
    let _ = writeln!(out, "#endif /* {macro_name} */");
    out
}

/// The C spelling of a type that may cross. `ffi.md` §1 is the table.
fn c_type(ty: &Type) -> &'static str {
    match ty {
        Type::Int => "int64_t",
        Type::Float => "double",
        Type::Bool => "bool",
        Type::Ptr => "void *",
        Type::Unit => "void",
        Type::Fixed(kind) => match (kind.signed, kind.bits) {
            (false, 8) => "uint8_t",
            (false, 16) => "uint16_t",
            (false, 32) => "uint32_t",
            (false, 64) => "uint64_t",
            (true, 8) => "int8_t",
            (true, 16) => "int16_t",
            (true, 32) => "int32_t",
            // `IntKind::parse` refuses a signed 64 — that is `Type::Int` — so
            // this arm is the widths that do not exist rather than `I64`.
            _ => "int64_t",
        },
        // Unreachable: `export_errors` refuses the declaration before anything
        // gets here. Rendered as a comment rather than panicking, because a
        // compiler that aborts on its own invariant is worse than one that
        // writes something a C compiler will reject with a clear message.
        _ => "/* a type that cannot cross */ void *",
    }
}

/// `link-shortener` becomes `LINK_SHORTENER`, for an include guard.
fn shout(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_uppercase() } else { '_' })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use khora_types::IntKind;

    fn signature(params: Vec<Type>, ret: Type) -> Signature {
        Signature {
            is_extern: true,
            generics: Vec::new(),
            bounds: Default::default(),
            requires: Type::row(Vec::new(), None),
            raises: Type::row(Vec::new(), None),
            params,
            ret,
        }
    }

    /// The trap control surface is declared, so a host needs no hand-written
    /// `extern` for the functions the library already publishes.
    #[test]
    fn the_header_declares_the_trap_controls() {
        let out = render("x", &[]);
        assert!(out.contains("void khora_set_trap_policy(int contain);"), "{out}");
        assert!(out.contains("int khora_trapped(void);"), "{out}");
        assert!(out.contains("void khora_clear_trap(void);"), "{out}");
        // And says which half is a promise and which is an instrument.
        assert!(out.contains("Diagnostic, not a contract"), "{out}");
    }

    #[test]
    fn a_header_guards_itself_and_declares_what_it_was_given() {
        let out = render(
            "pricing",
            &[("price".to_string(), signature(vec![Type::Int, Type::Int], Type::Int))],
        );
        assert!(out.contains("#ifndef KHORA_PRICING_H"), "{out}");
        assert!(out.contains("#define KHORA_PRICING_H"), "{out}");
        assert!(out.contains("int64_t price(int64_t a0, int64_t a1);"), "{out}");
        assert!(out.contains("extern \"C\" {"), "C++ can include it too: {out}");
    }

    /// **`void`, not an empty list.** `f()` in C takes unspecified arguments
    /// and checks nothing at the call site, which is the opposite of the point.
    #[test]
    fn a_function_with_no_parameters_says_void() {
        let out = render("x", &[("tick".to_string(), signature(Vec::new(), Type::Unit))]);
        assert!(out.contains("void tick(void);"), "{out}");
    }

    #[test]
    fn the_fixed_widths_keep_their_names() {
        let out = render(
            "x",
            &[(
                "narrow".to_string(),
                signature(
                    vec![
                        Type::Fixed(IntKind { signed: false, bits: 8 }),
                        Type::Fixed(IntKind { signed: true, bits: 32 }),
                    ],
                    Type::Bool,
                ),
            )],
        );
        assert!(out.contains("bool narrow(uint8_t a0, int32_t a1);"), "{out}");
    }

    #[test]
    fn a_name_with_a_dash_still_makes_a_legal_macro() {
        let out = render("link-shortener", &[]);
        assert!(out.contains("KHORA_LINK_SHORTENER_H"), "{out}");
    }
}
