//! Counting what a value held inline holds.
//!
//! An inline value has no header, so nothing counts *it* and nothing can hang
//! a drop routine off it. What it holds is still counted: a `Step` laid out
//! flat carries a `List`, and a copy of the `Step` is a copy of that pointer.
//!
//! So the counting moves outwards, from the value to its fields, and this is
//! where it happens. One generated routine per type rather than a walk emitted
//! at each site, because three unrelated places need the same walk -- a
//! binding going out of scope, a field of a boxed object, and the box an
//! inline value crosses a word boundary in -- and three copies of a tag guard
//! is three places to get it wrong.

use super::*;

use inkwell::IntPredicate;

impl<'ctx> Backend<'ctx> {
    /// Whether a value of this type owns a reference somebody has to release.
    ///
    /// A boxed value owns itself. An inline one owns whatever its fields own.
    /// A machine word owns nothing, and neither does an inline value of
    /// nothing but machine words -- which is every type `Fields::Scalars`
    /// allowed, and why this question did not exist before.
    pub fn owns_a_reference(&self, ty: &Type) -> bool {
        khora_perceus::owns_a_reference(ty, &self.unboxed)
    }

    /// The tag of the one variant that carries the payload.
    ///
    /// `None` where every case is nullary, or where there is only one and so
    /// nothing to discriminate. The criterion allows exactly one carrying
    /// case, which is what makes a single guard enough: the fields are live
    /// under that tag and under no other.
    fn carrying_case(&self, ty: &Type) -> Option<u32> {
        if self.cases_of(ty) <= 1 {
            return None;
        }
        let variants = self.variants_for(ty);
        variants.iter().position(|v| !v.fields.is_empty()).map(|i| i as u32)
    }

    /// The routine that releases what an inline value holds, or `None` where
    /// it holds nothing counted.
    pub fn inline_release(&mut self, ty: &Type) -> Option<FunctionValue<'ctx>> {
        self.inline_walk(ty, Adjust::Down)
    }

    /// The routine that adds a reference to what an inline value holds.
    ///
    /// The mirror of [`Self::inline_release`], and generated by the same walk:
    /// two routines that disagree about which fields a value has would be a
    /// leak in one direction and a use after free in the other.
    pub fn inline_retain(&mut self, ty: &Type) -> Option<FunctionValue<'ctx>> {
        self.inline_walk(ty, Adjust::Up)
    }

    fn inline_walk(&mut self, ty: &Type, adjust: Adjust) -> Option<FunctionValue<'ctx>> {
        if !self.unboxed.holds(ty) {
            return None;
        }
        let key = super::glue::type_key(ty);
        let cached = match adjust {
            Adjust::Up => self.inline_retains.get(&key),
            Adjust::Down => self.inline_releases.get(&key),
        };
        if let Some(found) = cached {
            return *found;
        }

        let payload = self.unboxed.payload(ty).unwrap_or_default();
        let shape = self.unboxed_type(ty);
        let answer = match shape {
            Some(shape) if payload.iter().any(|f| self.owns_a_reference(f)) => {
                Some(self.emit_inline_walk(ty, &key, shape, &payload, adjust))
            }
            _ => None,
        };
        match adjust {
            Adjust::Up => self.inline_retains.insert(key, answer),
            Adjust::Down => self.inline_releases.insert(key, answer),
        };
        answer
    }

    /// Emits the walk: a tag guard where there is a tag, then a field each.
    ///
    /// **Recorded before it is emitted**, so that a type reached from its own
    /// field asks for the routine that is being built rather than starting a
    /// second one. An inline type cannot reach itself -- the criterion refuses
    /// a recursive type outright -- but the cache is written first anyway,
    /// because the cost is a line and the alternative is unbounded recursion
    /// the day the criterion is loosened.
    fn emit_inline_walk(
        &mut self,
        ty: &Type,
        key: &str,
        shape: inkwell::types::StructType<'ctx>,
        payload: &[Type],
        adjust: Adjust,
    ) -> FunctionValue<'ctx> {
        let verb = match adjust {
            Adjust::Up => "retain",
            Adjust::Down => "release",
        };
        let f = self.module.add_function(
            &format!("kh${verb}${key}"),
            self.ctx.void_type().fn_type(&[shape.into()], false),
            Some(Linkage::Internal),
        );
        match adjust {
            Adjust::Up => self.inline_retains.insert(key.to_string(), Some(f)),
            Adjust::Down => self.inline_releases.insert(key.to_string(), Some(f)),
        };

        let saved = self.builder.get_insert_block();
        let entry = self.ctx.append_basic_block(f, "entry");
        let done = self.ctx.append_basic_block(f, "done");
        self.builder.position_at_end(entry);
        let whole = f
            .get_nth_param(0)
            .expect("the value to walk")
            .into_struct_value();

        // The payload belongs to one case, so under any other tag those
        // registers hold nothing and touching them is a wild free.
        if let Some(carrying) = self.carrying_case(ty) {
            let held = self.ctx.append_basic_block(f, "carrying");
            let tag = self
                .builder
                .build_extract_value(whole, 0, "case")
                .expect("reading an inline tag")
                .into_int_value();
            let expected = self.ctx.i32_type().const_int(u64::from(carrying), false);
            let is_carrying = self
                .builder
                .build_int_compare(IntPredicate::EQ, tag, expected, "carries")
                .expect("comparing a tag");
            self.builder
                .build_conditional_branch(is_carrying, held, done)
                .expect("guarding a payload walk");
            self.builder.position_at_end(held);
        }

        for (index, field) in payload.iter().enumerate() {
            if !self.owns_a_reference(field) {
                continue;
            }
            let at = self.unboxed_field_at(ty, index);
            let value = self
                .builder
                .build_extract_value(whole, at, "held")
                .expect("reading an inline field");
            self.adjust_held(value, field, adjust);
        }
        self.builder.build_unconditional_branch(done).expect("leaving the walk");

        self.builder.position_at_end(done);
        self.builder.build_return(None).expect("returning from an inline walk");
        if let Some(block) = saved {
            self.builder.position_at_end(block);
        }
        f
    }

    /// One field: a pointer counted directly, an inline value walked in turn.
    ///
    /// The runtime's `khora_dup` and `khora_drop` rather than the inlined
    /// arithmetic `Lower` emits. This is the rarer path by construction --
    /// a value is walked once per copy of it, not once per field access --
    /// and a call keeps the walk one routine instead of one per call site.
    pub(super) fn adjust_held(&mut self, value: BasicValueEnum<'ctx>, ty: &Type, adjust: Adjust) {
        if is_boxed(ty, &self.unboxed) {
            match adjust {
                Adjust::Up => {
                    self.builder
                        .build_call(self.rt.dup, &[value.into()], "")
                        .expect("keeping a held reference");
                }
                Adjust::Down => {
                    let glue = self.drop_glue(ty);
                    self.builder
                        .build_call(self.rt.drop, &[value.into(), glue.into()], "")
                        .expect("releasing a held reference");
                }
            }
            return;
        }
        let Some(walk) = self.inline_walk(ty, adjust) else { return };
        self.builder
            .build_call(walk, &[value.into()], "")
            .expect("walking a held inline value");
    }

    /// How a structure that *holds* a value as one word lets go of it.
    ///
    /// A cell, a channel and a fiber's answer each keep one machine word and
    /// release it when they are done with it. For a boxed value that is the
    /// object's own drop glue. For an inline one the word is the box it
    /// crossed in, and [`Self::spill_glue`] is that box's -- the type's glue
    /// is the wrong shape for it, walking an object's fields where the box has
    /// a whole value.
    pub fn holding_glue(&mut self, ty: &Type) -> PointerValue<'ctx> {
        if self.unboxed.holds(ty) {
            return self.spill_glue(ty);
        }
        self.drop_glue(ty)
    }

    /// The routine that releases an inline value sitting at a given address.
    ///
    /// An array's element, which is in the array rather than pointed at from
    /// it -- so the runtime, which cannot know the type, hands over the slot's
    /// address and this reads the value out of it.
    ///
    /// A null pointer where the element holds nothing counted, which is what
    /// tells the runtime there is nothing to walk.
    pub fn element_glue(&mut self, ty: &Type) -> PointerValue<'ctx> {
        if !self.unboxed.holds(ty) || !self.owns_a_reference(ty) {
            return self.null_pointer();
        }
        let key = super::glue::type_key(ty);
        let name = format!("kh$release_at${key}");
        if let Some(f) = self.module.get_function(&name) {
            return f.as_global_value().as_pointer_value();
        }
        let Some(shape) = self.unboxed_type(ty) else { return self.null_pointer() };
        let Some(walk) = self.inline_release(ty) else { return self.null_pointer() };

        let ptr = self.ctx.ptr_type(AddressSpace::default());
        let f = self.module.add_function(
            &name,
            self.ctx.void_type().fn_type(&[ptr.into()], false),
            Some(Linkage::Internal),
        );
        let saved = self.builder.get_insert_block();
        let entry = self.ctx.append_basic_block(f, "entry");
        self.builder.position_at_end(entry);
        let at = f.get_nth_param(0).expect("the element").into_pointer_value();
        let value = self.builder.build_load(shape, at, "element").expect("reading an element");
        self.builder.build_call(walk, &[value.into()], "").expect("releasing what it held");
        self.builder.build_return(None).expect("returning from an element's glue");
        if let Some(block) = saved {
            self.builder.position_at_end(block);
        }
        f.as_global_value().as_pointer_value()
    }

    /// `drop_fields` for the box an inline value crosses a word boundary in.
    ///
    /// The box holds one aggregate at slot zero rather than a field list, so
    /// the drop glue for the *type* is the wrong shape for it -- that one
    /// walks an object's fields at an object's offsets, and this one has a
    /// value where the fields would be.
    ///
    /// Needed only where a structure *holds* the box. A hand-off frees it
    /// through `word_to_value`, which reads the value out first, so the fields
    /// have moved and the box must be freed without releasing them.
    pub fn spill_glue(&mut self, ty: &Type) -> PointerValue<'ctx> {
        if !self.unboxed.holds(ty) || !self.owns_a_reference(ty) {
            return self.null_pointer();
        }
        let key = super::glue::type_key(ty);
        if let Some(Some(f)) = self.spill_glue.get(&key) {
            return f.as_global_value().as_pointer_value();
        }
        let Some(shape) = self.unboxed_type(ty) else { return self.null_pointer() };
        let Some(walk) = self.inline_release(ty) else { return self.null_pointer() };

        let ptr = self.ctx.ptr_type(AddressSpace::default());
        let f = self.module.add_function(
            &format!("kh$drop_fields$spilled${key}"),
            self.ctx.void_type().fn_type(&[ptr.into()], false),
            Some(Linkage::Internal),
        );
        self.spill_glue.insert(key, Some(f));

        let saved = self.builder.get_insert_block();
        let entry = self.ctx.append_basic_block(f, "entry");
        self.builder.position_at_end(entry);
        let object = f.get_nth_param(0).expect("the box").into_pointer_value();
        let slot = crate::runtime::field_pointer(self.ctx, &self.builder, object, 0);
        let value = self
            .builder
            .build_load(shape, slot, "spilled")
            .expect("reading a spilled value");
        self.builder.build_call(walk, &[value.into()], "").expect("releasing what it held");
        self.builder.build_return(None).expect("returning from a spill's glue");
        if let Some(block) = saved {
            self.builder.position_at_end(block);
        }
        f.as_global_value().as_pointer_value()
    }
}

/// Which way a walk moves a reference count.
#[derive(Clone, Copy, PartialEq, Eq)]
pub(crate) enum Adjust {
    /// A copy was made and every reference in it is one more.
    Up,
    /// A copy went away.
    Down,
}
