//! Counting what a value held inline holds.
//!
//! An inline value has no header, so nothing counts *it* and nothing can hang
//! a drop routine off it. What it holds is still counted: a `Step` laid out
//! flat carries a `List`, and a copy of the `Step` is a copy of that pointer.
//!
//! So the counting moves outwards, from the value to its fields, and this is
//! where it happens. One generated routine per type rather than a walk emitted
//! at each site, because three unrelated places need the same walk -- a
//! binding going out of scope, a field of a boxed object, and the box an
//! inline value crosses a word boundary in -- and three copies of a tag guard
//! is three places to get it wrong.

use super::*;


impl<'ctx> Backend<'ctx> {
    /// Whether a value of this type owns a reference somebody has to release.
    ///
    /// A boxed value owns itself. An inline one owns whatever its fields own.
    /// A machine word owns nothing, and neither does an inline value of
    /// nothing but machine words -- which is every type `Fields::Scalars`
    /// allowed, and why this question did not exist before.
    pub fn owns_a_reference(&self, ty: &Type) -> bool {
        khora_perceus::owns_a_reference(ty, &self.unboxed)
    }

    /// The routine that releases what an inline value holds, or `None` where
    /// it holds nothing counted.
    pub fn inline_release(&mut self, ty: &Type) -> Option<FunctionValue<'ctx>> {
        self.inline_walk(ty, Adjust::Down)
    }

    /// The routine that adds a reference to what an inline value holds.
    ///
    /// The mirror of [`Self::inline_release`], and generated by the same walk:
    /// two routines that disagree about which fields a value has would be a
    /// leak in one direction and a use after free in the other.
    pub fn inline_retain(&mut self, ty: &Type) -> Option<FunctionValue<'ctx>> {
        self.inline_walk(ty, Adjust::Up)
    }

    fn inline_walk(&mut self, ty: &Type, adjust: Adjust) -> Option<FunctionValue<'ctx>> {
        if !self.unboxed.holds(ty) {
            return None;
        }
        let key = super::glue::type_key(ty);
        let cached = match adjust {
            Adjust::Up => self.inline_retains.get(&key),
            Adjust::Down => self.inline_releases.get(&key),
        };
        if let Some(found) = cached {
            return *found;
        }

        let payloads = self.unboxed.payloads(ty).unwrap_or_default();
        let shape = self.unboxed_type(ty);
        let owning = payloads.iter().any(|(_, f)| f.iter().any(|t| self.owns_a_reference(t)));
        let answer = match shape {
            Some(shape) if owning => {
                Some(self.emit_inline_walk(ty, &key, shape, &payloads, adjust))
            }
            _ => None,
        };
        match adjust {
            Adjust::Up => self.inline_retains.insert(key, answer),
            Adjust::Down => self.inline_releases.insert(key, answer),
        };
        answer
    }

    /// Emits the walk: a tag guard where there is a tag, then a field each.
    ///
    /// **Recorded before it is emitted**, so that a type reached from its own
    /// field asks for the routine that is being built rather than starting a
    /// second one. An inline type cannot reach itself -- the criterion refuses
    /// a recursive type outright -- but the cache is written first anyway,
    /// because the cost is a line and the alternative is unbounded recursion
    /// the day the criterion is loosened.
    fn emit_inline_walk(
        &mut self,
        ty: &Type,
        key: &str,
        shape: inkwell::types::StructType<'ctx>,
        payloads: &[(u32, Vec<Type>)],
        adjust: Adjust,
    ) -> FunctionValue<'ctx> {
        let verb = match adjust {
            Adjust::Up => "retain",
            Adjust::Down => "release",
        };
        let f = self.module.add_function(
            &format!("kh${verb}${key}"),
            self.ctx.void_type().fn_type(&[shape.into()], false),
            Some(Linkage::Internal),
        );
        match adjust {
            Adjust::Up => self.inline_retains.insert(key.to_string(), Some(f)),
            Adjust::Down => self.inline_releases.insert(key.to_string(), Some(f)),
        };

        let saved = self.builder.get_insert_block();
        let entry = self.ctx.append_basic_block(f, "entry");
        let done = self.ctx.append_basic_block(f, "done");
        self.builder.position_at_end(entry);
        let whole = f
            .get_nth_param(0)
            .expect("the value to walk")
            .into_struct_value();

        // **Only the slots this value's own tag names.** A variant's payload
        // is live under its tag and under no other, and the slots are shared,
        // so walking the wrong variant's field list reads one thing as
        // another -- a wild free in one direction and a leak in the other.
        //
        // Where there is nothing to discriminate the guard is not emitted at
        // all, which is every record and every type that had a single carrier
        // before unions.
        if self.cases_of(ty) > 1 {
            let tag = self
                .builder
                .build_extract_value(whole, 0, "case")
                .expect("reading an inline tag")
                .into_int_value();
            let mut arms = Vec::with_capacity(payloads.len());
            for (case, fields) in payloads {
                if !fields.iter().any(|t| self.owns_a_reference(t)) {
                    continue;
                }
                let block = self.ctx.append_basic_block(f, &format!("case.{case}"));
                arms.push((self.ctx.i32_type().const_int(u64::from(*case), false), block));
                self.builder.position_at_end(block);
                self.walk_fields(whole, ty, fields, adjust);
                self.builder.build_unconditional_branch(done).expect("leaving a case");
            }
            self.builder.position_at_end(entry);
            // Everything else -- a nullary case, or one that holds nothing
            // counted -- falls through to the return.
            self.builder.build_switch(tag, done, &arms).expect("switching on an inline tag");
        } else {
            let fields = payloads.first().map(|(_, f)| f.as_slice()).unwrap_or(&[]);
            self.walk_fields(whole, ty, fields, adjust);
            self.builder.build_unconditional_branch(done).expect("leaving the walk");
        }

        self.builder.position_at_end(done);
        self.builder.build_return(None).expect("returning from an inline walk");
        if let Some(block) = saved {
            self.builder.position_at_end(block);
        }
        f
    }

    /// Every field of one variant that holds something counted.
    fn walk_fields(
        &mut self,
        whole: inkwell::values::StructValue<'ctx>,
        ty: &Type,
        fields: &[Type],
        adjust: Adjust,
    ) {
        for (index, field) in fields.iter().enumerate() {
            if !self.owns_a_reference(field) {
                continue;
            }
            let value = self.read_inline(whole, ty, index, field);
            self.adjust_held(value, field, adjust);
        }
    }

    /// One field: a pointer counted directly, an inline value walked in turn.
    ///
    /// The runtime's `khora_dup` and `khora_drop` rather than the inlined
    /// arithmetic `Lower` emits. This is the rarer path by construction --
    /// a value is walked once per copy of it, not once per field access --
    /// and a call keeps the walk one routine instead of one per call site.
    pub(super) fn adjust_held(&mut self, value: BasicValueEnum<'ctx>, ty: &Type, adjust: Adjust) {
        if is_boxed(ty, &self.unboxed) {
            match adjust {
                Adjust::Up => {
                    self.builder
                        .build_call(self.rt.dup, &[value.into()], "")
                        .expect("keeping a held reference");
                }
                Adjust::Down => {
                    let glue = self.drop_glue(ty);
                    self.builder
                        .build_call(self.rt.drop, &[value.into(), glue.into()], "")
                        .expect("releasing a held reference");
                }
            }
            return;
        }
        let Some(walk) = self.inline_walk(ty, adjust) else { return };
        self.builder
            .build_call(walk, &[value.into()], "")
            .expect("walking a held inline value");
    }

    /// How a structure that *holds* a value as one word lets go of it.
    ///
    /// A cell, a channel and a fiber's answer each keep one machine word and
    /// release it when they are done with it. For a boxed value that is the
    /// object's own drop glue. For an inline one the word is the box it
    /// crossed in, and [`Self::spill_glue`] is that box's -- the type's glue
    /// is the wrong shape for it, walking an object's fields where the box has
    /// a whole value.
    pub fn holding_glue(&mut self, ty: &Type) -> PointerValue<'ctx> {
        if self.unboxed.holds(ty) {
            return self.spill_glue(ty);
        }
        self.drop_glue(ty)
    }

    /// The routine that releases an inline value sitting at a given address.
    ///
    /// An array's element, which is in the array rather than pointed at from
    /// it -- so the runtime, which cannot know the type, hands over the slot's
    /// address and this reads the value out of it.
    ///
    /// A null pointer where the element holds nothing counted, which is what
    /// tells the runtime there is nothing to walk.
    pub fn element_glue(&mut self, ty: &Type) -> PointerValue<'ctx> {
        if !self.unboxed.holds(ty) || !self.owns_a_reference(ty) {
            return self.null_pointer();
        }
        let key = super::glue::type_key(ty);
        let name = format!("kh$release_at${key}");
        if let Some(f) = self.module.get_function(&name) {
            return f.as_global_value().as_pointer_value();
        }
        let Some(shape) = self.unboxed_type(ty) else { return self.null_pointer() };
        let Some(walk) = self.inline_release(ty) else { return self.null_pointer() };

        let ptr = self.ctx.ptr_type(AddressSpace::default());
        let f = self.module.add_function(
            &name,
            self.ctx.void_type().fn_type(&[ptr.into()], false),
            Some(Linkage::Internal),
        );
        let saved = self.builder.get_insert_block();
        let entry = self.ctx.append_basic_block(f, "entry");
        self.builder.position_at_end(entry);
        let at = f.get_nth_param(0).expect("the element").into_pointer_value();
        let value = self.builder.build_load(shape, at, "element").expect("reading an element");
        self.builder.build_call(walk, &[value.into()], "").expect("releasing what it held");
        self.builder.build_return(None).expect("returning from an element's glue");
        if let Some(block) = saved {
            self.builder.position_at_end(block);
        }
        f.as_global_value().as_pointer_value()
    }

    /// Counts what an inline value holds, given the box it crossed in.
    ///
    /// **For a reader that copies rather than takes.** A value held inline
    /// travels as one word pointing at a box, and reading it back out copies
    /// the fields into the reading frame -- pointers and all. Where the
    /// structure it came from *gave up* its reference, as a channel's queue
    /// does, that copy is the only owner and nothing is owed. Where the
    /// structure keeps one, as a fiber's stored answer and a `Shared` cell do,
    /// the copy is a second owner of a pointer counted once, and the second
    /// release of it aborts the process.
    ///
    /// Walks the fields rather than the box: the box's own count is already
    /// right, and it is what the value is *in* rather than what it is.
    ///
    /// **Before [`Self::word_to_value`], never after.** That frees the reader's
    /// reference to the box, and where it was the last one the fields are
    /// gone by the time a later walk would load them.
    ///
    /// Loads through the word unconditionally, so a caller that can be handed
    /// a zero (a stopped fiber's answer) must branch around it first.
    pub fn retain_spilled(&mut self, word: inkwell::values::IntValue<'ctx>, ty: &Type) {
        let Some(walk) = self.inline_retain(ty) else { return };
        let Some(shape) = self.unboxed_type(ty) else { return };
        let ptr = self.ctx.ptr_type(AddressSpace::default());
        let object = self
            .builder
            .build_int_to_ptr(word, ptr, "spilled.retain")
            .expect("a word as a spilled value");
        let slot = crate::runtime::field_pointer(self.ctx, &self.builder, object, 0);
        let value = self
            .builder
            .build_load(shape, slot, "spilled.fields")
            .expect("reading a spilled value to count it");
        self.builder
            .build_call(walk, &[value.into()], "")
            .expect("counting what a spilled value holds");
    }

    /// A word some structure *keeps* read back as a value the reader owns.
    ///
    /// [`Self::word_to_value`] is for a hand-off: it frees the box with null
    /// glue because the fields have moved. A cell's value has not moved -- the
    /// cell still holds the box -- so the reader counts the fields first
    /// ([`Self::retain_spilled`]) and then lets go of its reference to the box
    /// with the box's own glue.
    ///
    /// **The glue, not null, because the reader's reference may be the last.**
    /// A cell that is a temporary, `Shared::get(Shared::of(r))`, is released
    /// before the value is read, and then this is the free that takes the box.
    /// Null glue there leaked every field once per read: the box's hold on
    /// them went with it, uncounted. Where the cell survives the glue does
    /// not run, so the one routine is right in both cases.
    pub fn reload_kept(
        &mut self,
        word: inkwell::values::IntValue<'ctx>,
        ty: &Type,
    ) -> BasicValueEnum<'ctx> {
        let Some(shape) = self.unboxed_type(ty).filter(|_| self.unboxed.holds(ty)) else {
            return self.word_to_value(word, ty);
        };
        self.retain_spilled(word, ty);
        let ptr = self.ctx.ptr_type(AddressSpace::default());
        let object = self
            .builder
            .build_int_to_ptr(word, ptr, "kept")
            .expect("a word as the box a kept value is in");
        let slot = crate::runtime::field_pointer(self.ctx, &self.builder, object, 0);
        let value = self
            .builder
            .build_load(shape, slot, "kept.reload")
            .expect("reading a kept value");
        let glue = self.spill_glue(ty);
        self.builder
            .build_call(self.rt.drop, &[object.into(), glue.into()], "")
            .expect("letting go of the box a kept value is in");
        value
    }

    /// `drop_fields` for the box an inline value crosses a word boundary in.
    ///
    /// The box holds one aggregate at slot zero rather than a field list, so
    /// the drop glue for the *type* is the wrong shape for it -- that one
    /// walks an object's fields at an object's offsets, and this one has a
    /// value where the fields would be.
    ///
    /// Needed only where a structure *holds* the box. A hand-off frees it
    /// through `word_to_value`, which reads the value out first, so the fields
    /// have moved and the box must be freed without releasing them.
    pub fn spill_glue(&mut self, ty: &Type) -> PointerValue<'ctx> {
        if !self.unboxed.holds(ty) || !self.owns_a_reference(ty) {
            return self.null_pointer();
        }
        let key = super::glue::type_key(ty);
        if let Some(Some(f)) = self.spill_glue.get(&key) {
            return f.as_global_value().as_pointer_value();
        }
        let Some(shape) = self.unboxed_type(ty) else { return self.null_pointer() };
        let Some(walk) = self.inline_release(ty) else { return self.null_pointer() };

        let ptr = self.ctx.ptr_type(AddressSpace::default());
        let f = self.module.add_function(
            &format!("kh$drop_fields$spilled${key}"),
            self.ctx.void_type().fn_type(&[ptr.into()], false),
            Some(Linkage::Internal),
        );
        self.spill_glue.insert(key, Some(f));

        let saved = self.builder.get_insert_block();
        let entry = self.ctx.append_basic_block(f, "entry");
        self.builder.position_at_end(entry);
        let object = f.get_nth_param(0).expect("the box").into_pointer_value();
        let slot = crate::runtime::field_pointer(self.ctx, &self.builder, object, 0);
        let value = self
            .builder
            .build_load(shape, slot, "spilled")
            .expect("reading a spilled value");
        self.builder.build_call(walk, &[value.into()], "").expect("releasing what it held");
        self.builder.build_return(None).expect("returning from a spill's glue");
        if let Some(block) = saved {
            self.builder.position_at_end(block);
        }
        f.as_global_value().as_pointer_value()
    }
}

/// Which way a walk moves a reference count.
#[derive(Clone, Copy, PartialEq, Eq)]
pub(crate) enum Adjust {
    /// A copy was made and every reference in it is one more.
    Up,
    /// A copy went away.
    Down,
}
