#!/bin/sh
# The correctness baseline Phase 9 must preserve.
#
# Reuse analysis and FBIP change when memory is allocated and freed, and
# `docs/design/compatibility.md` decides that no program may depend on that. So
# what this checks is everything else: that programs still compile, still say
# the same things, and still answer ordinary clients the same way.
#
# It does not check throughput. That is `bench/README.md`, run by hand, because
# a number from a machine that is also running a test suite is not a number.
#
#     sh scripts/baseline.sh
#
# Exits non-zero on the first failure, and says which step.
set -e

root=$(cd "$(dirname "$0")/.." && pwd)
cd "$root"
khora="./target/debug/khora.exe"
[ -x "$khora" ] || khora="./target/debug/khora"

# `khora build` names its output with the host's executable extension, so a
# compiled program is `main.exe` on Windows and `main` everywhere else.
built() {
    [ -x "$1.exe" ] && printf '%s\n' "$1.exe" || printf '%s\n' "$1"
}

step() {
    printf '\n=== %s\n' "$1"
}

step 'the native suite'
cargo test --workspace --features llvm

step 'clippy, all targets'
cargo clippy --workspace --features llvm --all-targets -- -D warnings

step 'the corpus checks'
"$khora" check std
# One at a time, because each example is its own package: `ledger_service`
# depends on `packages/postgres`, and a check over the whole directory would
# resolve one manifest for four programs and find neither the dependency nor
# the reason it was missing.
for app in examples/*/; do
    "$khora" check "$app"
done
"$khora" check bench
# Packages live in the tree while they are written — `docs/roadmap.md` 13.12
# says why — so the baseline has to see them or they are not covered by it.
"$khora" check packages

step 'the corpus is formatted'
"$khora" fmt std --check
"$khora" fmt examples --check
"$khora" fmt bench --check
"$khora" fmt packages --check

step 'the standard library reference matches the standard library'
# `--check` writes nothing and fails if the checked-in pages are stale, which
# is the only way generated documentation stays true: a page regenerated by
# hand, sometimes, is a page that is wrong at the moment somebody reads it.
"$khora" doc std --out website/content/docs/stdlib/api --check

step 'the packages pass their own tests'
# A package whose tests nobody runs is a package with no tests. `khora test`
# compiles the `test` blocks into their own executable and runs it — the same
# path a user of the language would take.
"$khora" test packages/postgres

step 'every reference application builds'
# `ledger_service` is here for the same reason the packages are: it depends on
# `packages/postgres`, so building it is what catches a package change that
# breaks its only real consumer. It is not *run* here -- that needs a database,
# which `crates/khora-codegen-llvm/tests/postgres.rs` gates on KHORA_POSTGRES.
for app in examples/core_demo examples/risk_analyzer examples/link_shortener examples/ledger_service; do
    "$khora" build "$app"
done

step 'the reference applications that end on their own, run'
"$(built ./examples/core_demo/src/main)" > /dev/null

step 'an ordinary client gets ordinary answers'
sh "$root/scripts/http_conformance.sh"

# The runtime's reactor is `WSAPoll` here and `poll` everywhere else, and only
# one of those runs on this machine. WSL2 is a real kernel with real sockets, so
# it answers the question for Linux at no cost. Skipped rather than failed when
# there is no WSL: this is a Windows developer's extra check, not a requirement.
if command -v wsl >/dev/null 2>&1; then
    step 'the runtime on Linux, through WSL'
    # **Kept, not discarded.** This was `> /dev/null`, and when the Linux check
    # exited 101 the baseline log ended mid-sentence with no error anywhere in
    # it: every `say` header and every summary line that script writes goes to
    # stdout, so discarding stdout discards the part that names the step. It is
    # the same mistake the repeat loop inside `check-linux.sh` had, one level up.
    linux_log="${TMPDIR:-/tmp}/khora-baseline-linux.log"
    if ! sh "$root/scripts/check-linux.sh" > "$linux_log" 2>&1; then
        printf '  FAILED  the Linux check, kept at %s\n' "$linux_log" >&2
        tail -40 "$linux_log" >&2
        exit 1
    fi
    printf '  ok    khora-rt passes against the POSIX `poll`\n'
else
    printf '\n=== skipping the Linux check: no wsl\n'
fi

printf '\n=== baseline clean\n'
