import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

const autogeneratedGroup = (label, directory) => ({
  label,
  items: [{ autogenerate: { directory } }],
});

export default defineConfig({
  site: 'https://khoralang.com',
  base: '/docs',
  output: 'static',
  integrations: [
    starlight({
      title: 'Khora',
      description: 'Khora language documentation',
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/codyspate/khoralang',
        },
      ],
      sidebar: [
        autogeneratedGroup('Getting Started', 'getting-started'),
        autogeneratedGroup('Guide', 'guide'),
        autogeneratedGroup('Language Reference', 'reference'),
        autogeneratedGroup('Standard Library', 'stdlib'),
        autogeneratedGroup('Cookbook', 'cookbook'),
        autogeneratedGroup('Deployment', 'deployment'),
        autogeneratedGroup('Migration', 'migration'),
        autogeneratedGroup('Limitations', 'limitations'),
        autogeneratedGroup('Project', 'project'),
      ],
      editLink: {
        baseUrl: 'https://github.com/codyspate/khoralang/edit/main/website/content/docs/',
      },
    }),
  ],
});
