import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import khora from './src/syntax/khora.mjs';

const autogeneratedGroup = (label, directory) => ({
  label,
  items: [{ autogenerate: { directory } }],
});

const source = 'https://github.com/codyspate/khoralang';

// **Short paths, because they are what gets typed and pasted.**
//
// Section 17 of `docs/release-readiness.md` asks for direct paths to
// installation, releases, source, security reporting and contribution
// information. These are that: `khoralang.com/install` is a thing somebody can
// say out loud, and it survives the page it points at being reorganised.
//
// The three that leave the site go to files rather than to pages on purpose.
// `SECURITY.md` and `CONTRIBUTING.md` are read by people arriving from a
// vulnerability report or a pull request, and both are places where the
// canonical text is the one in the repository being contributed to.
const shortPaths = {
  '/install': '/docs/getting-started/installation/',
  '/docs/install': '/docs/getting-started/installation/',
  '/guide': '/docs/guide/',
  '/reference': '/docs/reference/',
  '/stdlib': '/docs/stdlib/',
  '/versioning': '/docs/reference/compatibility/',
  '/limitations': '/docs/limitations/',
  '/releases': `${source}/releases`,
  '/source': source,
  '/security': `${source}/blob/main/SECURITY.md`,
  '/contributing': `${source}/blob/main/CONTRIBUTING.md`,
  '/changelog': `${source}/blob/main/CHANGELOG.md`,
};

export default defineConfig({
  site: 'https://khoralang.com',
  output: 'static',
  redirects: shortPaths,
  integrations: [
    starlight({
      title: 'Khora',
      description: 'Khora language documentation',
      logo: {
        src: './src/assets/khora-mark.svg',
        alt: 'Khora pipe operator mark',
      },
      favicon: '/favicon.svg',
      customCss: ['./src/styles/custom.css'],
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: source,
        },
      ],
      // The footer carries the revision this build was made from, and the
      // paths above. `src/components/Footer.astro` says why.
      components: {
        Footer: './src/components/Footer.astro',
      },
      expressiveCode: {
        shiki: {
          langs: [khora],
        },
      },
      sidebar: [
        autogeneratedGroup('Getting Started', 'docs/getting-started'),
        autogeneratedGroup('Guide', 'docs/guide'),
        autogeneratedGroup('Language Reference', 'docs/reference'),
        autogeneratedGroup('Standard Library', 'docs/stdlib'),
        autogeneratedGroup('Cookbook', 'docs/cookbook'),
        autogeneratedGroup('Deployment', 'docs/deployment'),
        autogeneratedGroup('Migration', 'docs/migration'),
        autogeneratedGroup('Performance', 'docs/performance'),
        autogeneratedGroup('Limitations', 'docs/limitations'),
      ],
      editLink: {
        baseUrl: `${source}/edit/main/website/content/`,
      },
    }),
  ],
});
