import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import khora from './src/syntax/khora.mjs';
import { current, versions } from './versions.mjs';
import { unversioned as unversionedPages } from './src/generated/redirects.js';

const autogeneratedGroup = (label, directory) => ({
  label,
  items: [{ autogenerate: { directory } }],
});

// **The sidebar is per version, because the sections are.** A release that
// added a `Deployment` section has one and an older release does not, so a
// single hand-written list would show a reader of the old tree links into the
// new one. Autogenerating from `docs/<id>/<section>` means each tree advertises
// exactly the pages it has.
const sectionsOf = (version) => [
  autogeneratedGroup('Getting Started', `docs/${version}/getting-started`),
  autogeneratedGroup('Language Reference', `docs/${version}/reference`),
  autogeneratedGroup('Standard Library', `docs/${version}/stdlib`),
  autogeneratedGroup('Cookbook', `docs/${version}/cookbook`),
  autogeneratedGroup('Deployment', `docs/${version}/deployment`),
  autogeneratedGroup('Migration', `docs/${version}/migration`),
  autogeneratedGroup('Performance', `docs/${version}/performance`),
  autogeneratedGroup('Limitations', `docs/${version}/limitations`),
];

const source = 'https://github.com/codyspate/khoralang';

// **Short paths, because they are what gets typed and pasted.**
//
// Section 17 of `docs/release-readiness.md` asks for direct paths to
// installation, releases, source, security reporting and contribution
// information. These are that: `khoralang.com/install` is a thing somebody can
// say out loud, and it survives the page it points at being reorganised.
//
// The three that leave the site go to files rather than to pages on purpose.
// `SECURITY.md` and `CONTRIBUTING.md` are read by people arriving from a
// vulnerability report or a pull request, and both are places where the
// canonical text is the one in the repository being contributed to.
// **The Guide's pages, where they went.**
//
// `docs/design/docs-urls.md` says a page that moves leaves a redirect, and
// fifteen of them moved at once: the Guide taught the same constructs the
// Reference specified, one page against one page, so it was dissolved into the
// Reference and the two sections that were genuinely distinct. These are the
// links already written down in other people's bookmarks and issues.
const guidePages = Object.fromEntries(
  Object.entries({
    '/docs/guide': 'reference/',
    '/docs/guide/values-and-functions': 'reference/expressions/',
    '/docs/guide/control-flow': 'reference/control-flow/',
    '/docs/guide/data-types': 'reference/types/',
    '/docs/guide/pattern-matching': 'reference/patterns/',
    '/docs/guide/pipelines': 'reference/expressions/',
    '/docs/guide/generics-and-traits': 'reference/generics/',
    '/docs/guide/errors-and-raises': 'reference/failures/',
    '/docs/guide/effects-and-capabilities': 'reference/capabilities/',
    '/docs/guide/resources-and-regions': 'reference/memory-and-resources/',
    '/docs/guide/fibers-and-nurseries': 'reference/concurrency/',
    '/docs/guide/shared-state': 'reference/sharing/',
    '/docs/guide/testing': 'reference/testing/',
    '/docs/guide/modules-and-packages': 'reference/modules-and-packages/',
    '/docs/guide/collections-and-strings': 'stdlib/',
  }).map(([from, to]) => [from, `/docs/${current}/${to}`]),
);

// **Every unversioned `/docs/...` path keeps working, by landing in the current
// version.** These are the links in other people's bookmarks, issues and Stack
// Overflow answers, written before there was a version segment to write. A
// reader following one gets the documentation for the release they can install,
// which is the same thing the path meant when they saved it.
const unversioned = { '/docs': `/docs/${current}/`, ...unversionedPages };

const shortPaths = {
  '/install': `/docs/${current}/getting-started/installation/`,
  '/docs/install': `/docs/${current}/getting-started/installation/`,
  '/guide': `/docs/${current}/reference/`,
  '/reference': `/docs/${current}/reference/`,
  '/stdlib': `/docs/${current}/stdlib/`,
  '/versioning': `/docs/${current}/reference/compatibility/`,
  '/limitations': `/docs/${current}/limitations/`,
  '/releases': `${source}/releases`,
  '/source': source,
  '/security': `${source}/blob/main/SECURITY.md`,
  '/contributing': `${source}/blob/main/CONTRIBUTING.md`,
  '/changelog': `${source}/blob/main/CHANGELOG.md`,
};

export default defineConfig({
  site: 'https://khoralang.com',
  output: 'static',
  redirects: { ...guidePages, ...unversioned, ...shortPaths },
  integrations: [
    starlight({
      title: 'Khora',
      description: 'Khora language documentation',
      logo: {
        src: './src/assets/khora-mark.svg',
        alt: 'Khora pipe operator mark',
      },
      favicon: '/favicon.svg',
      customCss: ['./src/styles/custom.css'],
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: source,
        },
      ],
      // The footer carries the revision this build was made from, and the
      // paths above. `src/components/Footer.astro` says why.
      components: {
        Footer: './src/components/Footer.astro',
      },
      expressiveCode: {
        shiki: {
          langs: [khora],
        },
      },
      // One group per version, each holding that version's own sections.
      // With a single version this reads as the sections alone, because
      // Starlight collapses a group whose label matches the only one there is —
      // and when v1 ships the reader gets a second heading rather than a
      // redesign.
      sidebar:
        versions.length === 1
          ? sectionsOf(versions[0].id)
          : versions.map((version) => ({
              label: version.id === current ? `${version.label} (current)` : version.label,
              collapsed: version.id !== current,
              items: sectionsOf(version.id),
            })),
      editLink: {
        baseUrl: `${source}/edit/main/website/content/`,
      },
    }),
  ],
});
